[package]
name = "gyrus-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Command-line BrainFuck interpreter"
license.workspace = true
repository.workspace = true

[[bin]]
name = "gyrus"
path = "src/main.rs"

[dependencies]
gyrus.workspace = true
clap.workspace = true
